package strategy;

public class Teste {

	public static void main(String[] args) {
		String esperado = "Oh Yes!     Friends to this ground.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, HAMLET, POLONIUS, LAERTES, VOLTIMAND, CORNELIUS, Lords, and Attendants\r\n"
				+ "Oh Yes!     And let thine eye look like a friend on Denmark.\r\n"
				+ "Oh Yes!     Sir, my good friend; I'll change that name with you:\r\n"
				+ "Oh Yes!     Those friends thou hast, and their adoption tried,\r\n"
				+ "Oh Yes!     For loan oft loses both itself and friend,\r\n"
				+ "So long...    Make thy two eyes, like stars, start from their spheres,\r\n"
				+ "Oh Yes!     O'ermaster 't as you may. And now, good friends,\r\n"
				+ "Oh Yes!     As you are friends, scholars and soldiers,\r\n"
				+ "Oh Yes!     A worthy pioner! Once more remove, good friends.\r\n"
				+ "So long...    As 'Well, well, we know,' or 'We could, an if we would,'\r\n"
				+ "So long...    Or 'If we list to speak,' or 'There be, an if they might,'\r\n"
				+ "Oh Yes!     May do, to express his love and friending to you,\r\n"
				+ "Oh Yes!     As thus, 'I know his father and his friends,\r\n"
				+ "So long...    That's not my meaning: but breathe his faults so quaintly\r\n"
				+ "So long...    As 'twere a thing a little soil'd i' the working, Mark you,\r\n"
				+ "Oh Yes!     'Good sir,' or so, or 'friend,' or 'gentleman,'\r\n"
				+ "Oh Yes!     At 'closes in the consequence,' at 'friend or so,'\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, ROSENCRANTZ, GUILDENSTERN, and Attendants\r\n"
				+ "Oh Yes!     Welcome, my good friends!\r\n"
				+ "Oh Yes!     Friend, look to 't.\r\n"
				+ "Oh Yes!     My excellent good friends! How dost thou,\r\n"
				+ "So long...    Guildenstern? Ah, Rosencrantz! Good lads, how do ye both?\r\n"
				+ "Oh Yes!     my good friends, deserved at the hands of fortune,\r\n"
				+ "So long...    substance of the ambitious is merely the shadow of a dream.\r\n"
				+ "Oh Yes!     beaten way of friendship, what make you at Elsinore?\r\n"
				+ "Oh Yes!     thank you: and sure, dear friends, my thanks are\r\n"
				+ "So long...    Why did you laugh then, when I said 'man delights not me'?\r\n"
				+ "So long...    O Jephthah, judge of Israel, what a treasure hadst thou!\r\n"
				+ "Oh Yes!     to see thee well. Welcome, good friends. O, my old\r\n"
				+ "Oh Yes!     friend! thy face is valenced since I saw thee last:\r\n"
				+ "Oh Yes!     Follow him, friends: we'll hear a play to-morrow.\r\n"
				+ "Oh Yes!     Dost thou hear me, old friend; can you play the\r\n"
				+ "Oh Yes!     My good friends, I'll leave you till night: you are\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, POLONIUS, OPHELIA, ROSENCRANTZ, and GUILDENSTERN\r\n"
				+ "So long...    The courtier's, soldier's, scholar's, eye, tongue, sword;\r\n"
				+ "So long...    How now, my lord! I will the king hear this piece of work?\r\n"
				+ "So long...    To feed and clothe thee? Why should the poor be flatter'd?\r\n"
				+ "So long...    Danish march. A flourish. Enter KING CLAUDIUS, QUEEN GERTRUDE, POLONIUS, OPHELIA, ROSENCRANTZ, GUILDENSTERN, and others\r\n"
				+ "So long...    mother looks, and my father died within these two hours.\r\n"
				+ "So long...    Enter a King and a Queen very lovingly; the Queen embracing him, and he her. She kneels, and makes show of protestation unto him. He takes her up, and declines his head upon her neck: lays him down upon a bank of flowers: she, seeing him asleep, leaves him. Anon comes in a fellow, takes off his crown, kisses it, and pours poison in the King's ears, and exit. The Queen returns; finds the King dead, and makes passionate action. The Poisoner, with some two or three Mutes, comes in again, seeming to lament with her. The dead body is carried away. The Poisoner wooes the Queen with gifts: she seems loath and unwilling awhile, but in the end accepts his love\r\n"
				+ "So long...    ashamed to show, he'll not shame to tell you what it means.\r\n"
				+ "Oh Yes!     The poor advanced makes friends of enemies.\r\n"
				+ "Oh Yes!     For who not needs shall never lack a friend,\r\n"
				+ "Oh Yes!     And who in want a hollow friend doth try,\r\n"
				+ "So long...    Thoughts black, hands apt, drugs fit, and time agreeing;\r\n"
				+ "Oh Yes!     you deny your griefs to your friend.\r\n"
				+ "So long...    Do you see yonder cloud that's almost in shape of a camel?\r\n"
				+ "Oh Yes!     Leave me, friends.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, ROSENCRANTZ, and GUILDENSTERN\r\n"
				+ "Oh Yes!     Friends both, go join you with some further aid:\r\n"
				+ "Oh Yes!     Come, Gertrude, we'll call up our wisest friends;\r\n"
				+ "So long...    and wife is one flesh; and so, my mother. Come, for England!\r\n"
				+ "So long...    There's tricks i' the world; and hems, and beats her heart;\r\n"
				+ "Oh Yes!     That, swoopstake, you will draw both friend and foe,\r\n"
				+ "Oh Yes!     To his good friends thus wide I'll ope my arms;\r\n"
				+ "So long...    love, remember: and there is pansies. that's for thoughts.\r\n"
				+ "Oh Yes!     Make choice of whom your wisest friends you will.\r\n"
				+ "Oh Yes!     And you must put me in your heart for friend,\r\n"
				+ "So long...    that is not guilty of his own death shortens not his own life.\r\n"
				+ "So long...    such-a-one's horse, when he meant to beg it; might it not?\r\n"
				+ "So long...    but to play at loggats with 'em? mine ache to think on't.\r\n"
				+ "So long...    this box; and must the inheritor himself have no more, ha?\r\n"
				+ "So long...    yours: for my part, I do not lie in't, and yet it is mine.\r\n"
				+ "So long...    'tis for the dead, not for the quick; therefore thou liest.\r\n"
				+ "So long...    One that was a woman, sir; but, rest her soul, she's dead.\r\n"
				+ "So long...    A whoreson mad fellow's it was: whose do you think it was?\r\n"
				+ "So long...    Enter Priest, & c. in procession; the Corpse of OPHELIA, LAERTES and Mourners following; KING CLAUDIUS, QUEEN GERTRUDE, their trains, & c\r\n"
				+ "So long...    The Attendants part them, and they come out of the grave\r\n"
				+ "So long...    Woo't weep? woo't fight? woo't fast? woo't tear thyself?\r\n"
				+ "So long...    spirit. Put your bonnet to his right use; 'tis for the head.\r\n"
				+ "So long...    His purse is empty already; all's golden words are spent.\r\n"
				+ "So long...    I knew you must be edified by the margent ere you had done.\r\n"
				+ "So long...    against the Danish. Why is this 'imponed,' as you call it?\r\n"
				+ "So long...    I mean, my lord, the opposition of your person in trial.\r\n"
				+ "So long...    if not, I will gain nothing but my shame and the odd hits.\r\n"
				+ "So long...    To this effect, sir; after what flourish your nature will.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, LAERTES, Lords, OSRIC, and Attendants with foils, & c\r\n"
				+ "So long...    LAERTES wounds HAMLET; then in scuffling, they change rapiers, and HAMLET wounds LAERTES\r\n"
				+ "Oh Yes!     O, yet defend me, friends; I am but hurt.\r\n"
				+ "So long...    A dead march. Exeunt, bearing off the dead bodies; after which a peal of ordnance is shot off\r\n";

		String resposta = "Oh Yes! Friends to this ground.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, HAMLET, POLONIUS, LAERTES, VOLTIMAND, CORNELIUS, Lords, and Attendants\r\n"
				+ "Oh Yes!    And let thine eye look like a friend on Denmark.\r\n"
				+ "Oh Yes!    Sir, my good friend; I'll change that name with you:\r\n"
				+ "Oh Yes!    Those friends thou hast, and their adoption tried,\r\n"
				+ "Oh Yes!    For loan oft loses both itself and friend,\r\n"
				+ "So long...    Make thy two eyes, like stars, start from their spheres,\r\n"
				+ "Oh Yes!    O'ermaster 't as you may. And now, good friends,\r\n"
				+ "Oh Yes!    As you are friends, scholars and soldiers,\r\n"
				+ "Oh Yes!    A worthy pioner! Once more remove, good friends.\r\n"
				+ "So long...    As 'Well, well, we know,' or 'We could, an if we would,'\r\n"
				+ "So long...    Or 'If we list to speak,' or 'There be, an if they might,'\r\n"
				+ "Oh Yes!    May do, to express his love and friending to you,\r\n"
				+ "Oh Yes!    As thus, 'I know his father and his friends,\r\n"
				+ "So long...    That's not my meaning: but breathe his faults so quaintly\r\n"
				+ "So long...    As 'twere a thing a little soil'd i' the working, Mark you,\r\n"
				+ "Oh Yes!    'Good sir,' or so, or 'friend,' or 'gentleman,'\r\n"
				+ "Oh Yes!    At 'closes in the consequence,' at 'friend or so,'\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, ROSENCRANTZ, GUILDENSTERN, and Attendants\r\n"
				+ "Oh Yes!    Welcome, my good friends!\r\n" + "Oh Yes!    Friend, look to 't.\r\n"
				+ "Oh Yes!    My excellent good friends! How dost thou,\r\n"
				+ "So long...    Guildenstern? Ah, Rosencrantz! Good lads, how do ye both?\r\n"
				+ "Oh Yes!    my good friends, deserved at the hands of fortune,\r\n"
				+ "So long...    substance of the ambitious is merely the shadow of a dream.\r\n"
				+ "Oh Yes!    beaten way of friendship, what make you at Elsinore?\r\n"
				+ "Oh Yes!    thank you: and sure, dear friends, my thanks are\r\n"
				+ "So long...    Why did you laugh then, when I said 'man delights not me'?\r\n"
				+ "So long...    O Jephthah, judge of Israel, what a treasure hadst thou!\r\n"
				+ "Oh Yes!    to see thee well. Welcome, good friends. O, my old\r\n"
				+ "Oh Yes!    friend! thy face is valenced since I saw thee last:\r\n"
				+ "Oh Yes!    Follow him, friends: we'll hear a play to-morrow.\r\n"
				+ "Oh Yes!    Dost thou hear me, old friend; can you play the\r\n"
				+ "Oh Yes!    My good friends, I'll leave you till night: you are\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, POLONIUS, OPHELIA, ROSENCRANTZ, and GUILDENSTERN\r\n"
				+ "So long...    The courtier's, soldier's, scholar's, eye, tongue, sword;\r\n"
				+ "So long...    How now, my lord! I will the king hear this piece of work?\r\n"
				+ "So long...    To feed and clothe thee? Why should the poor be flatter'd?\r\n"
				+ "So long...    Danish march. A flourish. Enter KING CLAUDIUS, QUEEN GERTRUDE, POLONIUS, OPHELIA, ROSENCRANTZ, GUILDENSTERN, and others\r\n"
				+ "So long...    mother looks, and my father died within these two hours.\r\n"
				+ "So long...    Enter a King and a Queen very lovingly; the Queen embracing him, and he her. She kneels, and makes show of protestation unto him. He takes her up, and declines his head upon her neck: lays him down upon a bank of flowers: she, seeing him asleep, leaves him. Anon comes in a fellow, takes off his crown, kisses it, and pours poison in the King's ears, and exit. The Queen returns; finds the King dead, and makes passionate action. The Poisoner, with some two or three Mutes, comes in again, seeming to lament with her. The dead body is carried away. The Poisoner wooes the Queen with gifts: she seems loath and unwilling awhile, but in the end accepts his love\r\n"
				+ "So long...    ashamed to show, he'll not shame to tell you what it means.\r\n"
				+ "Oh Yes!    The poor advanced makes friends of enemies.\r\n"
				+ "Oh Yes!    For who not needs shall never lack a friend,\r\n"
				+ "Oh Yes!    And who in want a hollow friend doth try,\r\n"
				+ "So long...    Thoughts black, hands apt, drugs fit, and time agreeing;\r\n"
				+ "Oh Yes!    you deny your griefs to your friend.\r\n"
				+ "So long...    Do you see yonder cloud that's almost in shape of a camel?\r\n"
				+ "Oh Yes!    Leave me, friends.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, ROSENCRANTZ, and GUILDENSTERN\r\n"
				+ "Oh Yes!    Friends both, go join you with some further aid:\r\n"
				+ "Oh Yes!    Come, Gertrude, we'll call up our wisest friends;\r\n"
				+ "So long...    and wife is one flesh; and so, my mother. Come, for England!\r\n"
				+ "So long...    There's tricks i' the world; and hems, and beats her heart;\r\n"
				+ "Oh Yes!    That, swoopstake, you will draw both friend and foe,\r\n"
				+ "Oh Yes!    To his good friends thus wide I'll ope my arms;\r\n"
				+ "So long...    love, remember: and there is pansies. that's for thoughts.\r\n"
				+ "Oh Yes!    Make choice of whom your wisest friends you will.\r\n"
				+ "Oh Yes!    And you must put me in your heart for friend,\r\n"
				+ "So long...    that is not guilty of his own death shortens not his own life.\r\n"
				+ "So long...    such-a-one's horse, when he meant to beg it; might it not?\r\n"
				+ "So long...    but to play at loggats with 'em? mine ache to think on't.\r\n"
				+ "So long...    this box; and must the inheritor himself have no more, ha?\r\n"
				+ "So long...    yours: for my part, I do not lie in't, and yet it is mine.\r\n"
				+ "So long...    'tis for the dead, not for the quick; therefore thou liest.\r\n"
				+ "So long...    One that was a woman, sir; but, rest her soul, she's dead.\r\n"
				+ "So long...    A whoreson mad fellow's it was: whose do you think it was?\r\n"
				+ "So long...    Enter Priest, & c. in procession; the Corpse of OPHELIA, LAERTES and Mourners following; KING CLAUDIUS, QUEEN GERTRUDE, their trains, & c\r\n"
				+ "So long...    The Attendants part them, and they come out of the grave\r\n"
				+ "So long...    Woo't weep? woo't fight? woo't fast? woo't tear thyself?\r\n"
				+ "So long...    spirit. Put your bonnet to his right use; 'tis for the head.\r\n"
				+ "So long...    His purse is empty already; all's golden words are spent.\r\n"
				+ "So long...    I knew you must be edified by the margent ere you had done.\r\n"
				+ "So long...    against the Danish. Why is this 'imponed,' as you call it?\r\n"
				+ "So long...    I mean, my lord, the opposition of your person in trial.\r\n"
				+ "So long...    if not, I will gain nothing but my shame and the odd hits.\r\n"
				+ "So long...    To this effect, sir; after what flourish your nature will.\r\n"
				+ "So long...    Enter KING CLAUDIUS, QUEEN GERTRUDE, LAERTES, Lords, OSRIC, and Attendants with foils, & c\r\n"
				+ "So long...    LAERTES wounds HAMLET; then in scuffling, they change rapiers, and HAMLET wounds LAERTES\r\n"
				+ "Oh Yes!    O, yet defend me, friends; I am but hurt.\r\n"
				+ "So long...    A dead march. Exeunt, bearing off the dead bodies; after which a peal of ordnance is shot off\r\n";
		System.out.println(esperado.equalsIgnoreCase(resposta));
	}
}